### ISSUE TITLE
Many issues to be fixed in your code

### ISSUE THREAD

**Issue by adrianolls** [thesudoteam/laravel-asset-manager#1] opened 2017-01-25 04:18 UTC
Basic issues like

Method called css, replacement with following code

if (is_array($libs))
        {
            foreach ($libs as $lib)
            {
                $html .= $this->makeCssLib($lib);
            }
        } else
            $html.= $this->makeCssLib($libs);
you can fix also URL file generation, a example of what i say is this

return [
    'assets' => [
        'auth' => [
            'css' => [
                'assets/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css',
                'assets/css/font-icons/entypo/css/entypo.css',
                'assets/css/notosan.css',
                'assets/css/bootstrap.css',
                'assets/css/neon-core.css',
                'assets/css/neon-theme.css',
                'assets/css/neon-forms.css',
                'assets/css/custom.css',
            ]
        ]
    ],
];

Output URLs are relational and not absolute.

**Comment by sudomabider** [comment] 2017-01-25 04:42
@adrianolls Thanks for the comment.

1. By the `css` method I assume you're referring to this?

```
public function css(...$libs)
{
    $html = '';
    foreach ($libs as $lib) {
        $html .= $this->makeCssLib($lib);
    }
    return $html;
}
```
Well `$libs` is always going to be an array because of the splat operator, i.e. `...$libs`. Did you encounter any errors with this code?

2. The relative URLs

My original motivation was to make it easier to call 3rd party libraries, mostly from CDN. Those are absolute urls anyway. For local files it's probably better to use `elixir` to compile them into a single or just a few files. I would not recommend using this package for local resources since they're pretty easy to call already.

However if you really believe there's a need to support local files please let me know or submit a PR.

3. The many issues to be fixed in my code

I'd be happy to know about any other issues to be fixed. This was a very casual package so apologize for any issues you've encountered.

**Comment by adrianolls** [comment] 2017-01-28 02:52
first issue is about a issue acessing only one asset, will thrown a exception, about second issue, why i'll install a asset manager where i can't call to local assets, a asset manager is suposed to manage any kind of asset right ?
or make specified readme file about be a exclusive app to 3rd party librarys.

i search your project from google, and i know you can improve your project, will make a huge difference for many devs that need a simple and fast tool to manage assets

**Comment by sudomabider** [comment] 2017-01-28 04:46
@adrianolls Thanks for the feedback. I'll try and give it some love.

**Comment by sudomabider** [comment] 2017-01-28 08:13
@adrianolls 

I've gone ahead and made some small improvements but I haven't been able to reproduce your first issue. 
> first issue is about a issue accessing only one asset, will throw an exception

Can you be more specific about the replication steps and the exception itself? There was a PHP 5.6 compatibility issue which I've fixed. Not sure if that's related to your exception though.

Feel free to test out `dev-master` and see if it helps (btw local assets should now be absolute urls 721b1fd16d466a9cc934f8f6c31e92016c87cbf7)

**Closed as completed** 2017-02-28 00:27 UTC
